spring:
  datasource:
    url: jdbc:tc:postgresql:16:///test_db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

apm:
  scheduler:
    enabled: false
  
  alert:
    evaluation:
      enabled: false
    notification:
      channels:
        - log

server:
  port: 0

logging:
  level:
    root: WARN
    com.apm.platform: INFO
